# Generated by Django 6.0 on 2025-12-30 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
    ]
