# Generated by Django 6.0 on 2026-01-01 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0003_alter_item_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='payments_app.item')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
