# Generated by Django 6.0 on 2026-01-01 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments_app', '0005_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'dollar'), ('ruble', 'RUB')], default='RUB', validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(3)]),
            preserve_default=False,
        ),
    ]
